openapi: 3.0.0
info:
  description: >
    Aiven is a modern fully-managed open source data platform for streaming,
    storing, and analyzing data on any public cloud. On Aiven Platform, you can
    operate your data infrastructure with a few devops tools: Aiven Console,
    Aiven Terraform Provider, Aiven CLI, and Aiven Operator for Kubernetes. All
    of them are built on an open secure powerful REST API for integration with
    custom tooling.


    The Aiven REST API provides programmatic access to Aiven.io services. To
    call the Aiven API, you can use either CLI tools (for example, cURL or Aiven
    CLI client) or GUI tools, such as the Aiven public API Postman collection.


    This Aiven API documentation will help you operate your Aiven organization,
    projects, or services programmatically by integrating your applications and
    processes with Aiven.


    Aiven's APIs (Application Programming Interfaces) power its platform for
    data management. Aiven has a number of REST APIs that can help you build
    strong and robust data infrastructure for your applications.


    The Aiven API is organized around core resources. Each core resource has
    multiple endpoints, which can be interacted with using different HTTP
    methods.


    ## Getting started


    Some content here.
  version: 1.0.0
  title: Aiven API docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: See our docs. about Swagger
  url: https://aiven.io/docs/tools/cli
servers:
  - url: http://petstore.swagger.io/v2
tags:
  - name: Accounts
    description: >-
      Operations on the organization level related to accounts, projects, teams,
      users, invites, billing groups, payment methods, credit cards,
      authentication methods, and more
    externalDocs:
      description: See our docs.
      url: http://swagger.io
  - name: Groups
    description: >-
      Groups of users in your organization to make it easier to manage access to
      your organization's resources.
    externalDocs:
      description: See our docs.
      url: https://aiven.io/docs/platform/howto/manage-groups
paths:
  /organization/{organization_id}/user-groups:
    $ref: paths/organization_organization_id_user-groups.yaml
  /organization/{organization_id}/user-groups/{user_group_id}:
    $ref: paths/organization_organization_id_user-groups_user_group_id.yaml
  /organization/{organization_id}/user-groups/{user_group_id}/members:
    $ref: >-
      paths/organization_organization_id_user-groups_user_group_id_members.yaml
components:
  securitySchemes:
    tokenAuth:
      description: >-
        Header should be of the format `authorization: aivenv1 <TOKEN>`. Tokens
        can be obtained from [your Aiven profile
        page](https://console.aiven.io/profile/auth)
      scheme: bearer
      type: http
    oauth2:
      type: oauth2
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://console.aiven.io/oauth/authorize
          tokenUrl: https://api.aiven.io/v1/oauth2/token
          scopes:
            all: Provide full access to the API
            accounts: Allow enumerating and reading accounts configuration
            accounts:read: Allow modifying account configuration
            accounts:write: Provides full access to authentication related API
            authentication: Provides full access to authentication related API
            authentication:read: >-
              Allow reading authentication related configuration on resources
              (user profile, accounts)
            authentication:write: >-
              Allow modifying authentication related configurations on resources
              (user profile, accounts)
            billing: Provide full access to billing APIs
            billing:read: Allow reading billing information and configuration
            billing:write: Allow writing billing configuration
            payments: Provide full access to payment method APIs
            payments:read: Allow reading the payment method configurations
            payments:write: Allows writing payment method configuration
            privatelink: Provide full access to private link APIs
            privatelink:read: >-
              Allow enumerating and reading private link items and
              configurations
            privatelink:write: Allow writing (creating, modifying, deleting) private link items
            projects: Provide full access to projects APIs
            projects:read: Allow enumerating projects and reading their configuration
            projects:write: Allow writing (creating, modifying, deleting) projects
            scim: Provide full access to SCIM operations
            scim:read: Allow reading SCIM endpoints
            scim:write: Allow writing (modifying) SCIM endpoints
            services: Provide full access to services APIs
            services:read: Allow enumerating services and reading their configuration
            services:write: Allow writing (creating, modifying, deleting) services
            static_ips: Provide full access to static IPs APIs
            static_ips:read: Allow enumerating and reading static IP items and configurations
            static_ips:write: Allow writing (creating, modifying, deleting) static IP items
            tickets: Provide full access to support ticket APIs
            tickets:read: Allow enumerating and reading support tickets
            tickets:write: Allow writing (creating, modifying) support tickets
            user: Provide full access to user profile APIs
            user:read: Allow reading user profile and configuration
            user:write: Allow writing (modifying) user profile and configuration
